### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by cibernicola** [BlinkDL/Hua#2]
Neither with the --api argument nor with --api and --listen it works:
![2022-11-04_13h49_01](https://user-images.githubusercontent.com/4579387/199976889-a5f5d1fd-c6ba-4c8c-b2c7-897378d141d3.png)

Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36)
WebUI: Commit hash: 81973091bc07c706d056809d89221bafcd01b38a

**Comment by BlinkDL** [comment]
Latest A1111 commit breaks PaintHua: 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5f0117154382eb0e2547c72630256681673e353b

You can manually comment out the "app.user_middleware = xxxx" line in webui.py to solve it.
