### ISSUE TITLE
[Feature request] Ask user if they want to leave the page, to prevent progress loss 

### ISSUE THREAD

**Issue by remixer-dec** [BlinkDL/Hua#3]
I lost an hour of progress by accidentally doing a "backwards" gesture on a touchpad.
A simple line `window.onbeforeunload = () => 1` can help to prevent this from happening.

P.S. Thank you for making this software, I was looking for a tool like this since the release of stable diffusion, it is quite convenient

**Comment by BlinkDL** [comment]
Done :)
