### ISSUE TITLE
Issue with update A1111 (webui.py) after install

### ISSUE THREAD

**Issue by vootox** [BlinkDL/Hua#4]
What to do regarding the git pull update error in response to the modified webui.py? 
Error: 

> Your local changes to the following files would be overwritten by merge: webui.py 

> Please commit your changes or stash them before you merge.

> Aborting

I don't know how to commit or stash (or if that may cause future updating issues as I have little experience with git).

**Comment by BlinkDL** [comment]
restore webui.py by uncommenting "app.user_middleware = ..." and then you can git pull

use the new method: --cors-allow-origins=https://www.painthua.com

**Comment by vootox** [comment]
Awesome!
