### ISSUE TITLE
colab not working with error "webui.py: error: unrecognized arguments: --cors-allow-origins=https://www.painthua.com"

### ISSUE THREAD

**Issue by mhnoni** [BlinkDL/Hua#7]
Edit: nvm, I think it got fixed after deleting SD from my gdrive. 

hi, when I add below line to auto TheLastBen colab
`share='--api --cors-allow-origins=https://www.painthua.com'`

I get the error:
webui.py: error: unrecognized arguments: --cors-allow-origins=https://www.painthua.com

Any tips?

**Comment by BlinkDL** [comment]
you need to update A1111 to latest version :)
